#!/usr/bin/env sh
# Print random secrets for every "# CHANGEME" value in Langfuse's official docker-compose.yml.
# The official compose reads each one as ${VAR:-default}, so passing this file with
# `docker compose --env-file` replaces the defaults without editing vendor files.
# Used by `make langfuse-up` to create infra/langfuse/langfuse.env (gitignored) once.
set -eu

rand() { openssl rand -hex "$1"; }

POSTGRES_PASSWORD=$(rand 16)
MINIO_ROOT_PASSWORD=$(rand 16)

cat <<EOF
# Generated by infra/langfuse/gen-env.sh. Do not commit.
# Changing these after the first start requires wiping the Langfuse volumes
# (see "Reset" in infra/langfuse/README.md), because the databases keep the old ones.

# No anonymous usage telemetry from the self-hosted instance (PO data stays local).
TELEMETRY_ENABLED=false

SALT=$(rand 16)
ENCRYPTION_KEY=$(rand 32)
NEXTAUTH_SECRET=$(rand 32)

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres

CLICKHOUSE_PASSWORD=$(rand 16)
REDIS_AUTH=$(rand 16)

MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
EOF
